name: Déploiement sur Serveur

on:
  push:
    branches: [ "main" ] # Se lance quand on push sur main
  workflow_dispatch:      # Permet de lancer manuellement

jobs:
  deploy-via-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Exécution des commandes sur le serveur
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 48.220.33.123
          username: Antonio
          password: 'DvpSecuWeb123'  
          port: 22
          script: |
            # 1. Se rendre dans le dossier
            cd /home/Antonio/sirva-frontend
            fuser -k 3000/tcp
            git pull
            
            # 2. Lancer Django Server
            # ATTENTION : J'utilise 'nohup' et '&' pour lancer ça en arrière-plan.
            # Sans ça, GitHub Actions restera bloqué à tourner à l'infini car le serveur ne rend jamais la main.
            npm install
            npm run dev -- -p 3000 > /dev/null 2>&1 &
            
