name: Merge Manuel Dev -> main

on:
  workflow_dispatch: # Ce mot-clé active le bouton de lancement manuel

jobs:
  release-job:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Requis pour pousser la fusion sur master

    steps:
      # 1. Récupération de tout l'historique
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Configuration de l'identité du robot
      - name: Configuration Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      # 3. Exécution de la fusion
      - name: Fusionner Dev dans main
        run: |
          # Bascule sur la branche de destination (main)
          git checkout main
          
          # On s'assure d'avoir la dernière version de main avant de commencer
          git pull origin main
          
          # On fusionne la branche dev
          echo "Fusion de origin/dev vers main..."
          git merge origin/dev --no-edit
          
          # On pousse le résultat
          git push origin main
